[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "facture-app"
version = "0.1.0"
description = "Qt app for facture management"
authors = [{ name = "Rius" }]
dependencies = [
    "PySide6",
    "Pyside6-Addons",
    "pytesseract",
    "Pillow",

]

[tool.setuptools.packages.find]
where = ["."]
